//! The private key on disk is a 32-byte Ed25519 seed, written as hex, and a key
//! generated by one version of the crate has to keep working under the next.
//! That question became live when ed25519-dalek moved from 2 to 3 and
//! `generate_keypair` was rewritten to fill the seed itself, because
//! `SigningKey::generate` now demands an infallible CryptoRng and the OS
//! generator is fallible.
//!
//! What the existing signing tests check is that `generate_keypair` and
//! `load_signing_key` agree with each other. That is a real check and it is
//! sharper than it looks: breaking the derivation on one side only, and breaking
//! the stored format on what looked like both sides, each turned
//! `test_e2e_records_can_be_signed_and_tampering_is_caught` red. But agreement
//! between the two halves is all it is. Both halves go through the library's own
//! `to_bytes`/`from_bytes`, so a library that changed what those mean would move
//! them together, and a suite that only round-trips in one process cannot see the
//! difference between "these two agree" and "these two agree with Ed25519".
//!
//! The two constants below supply that missing half. Neither is derived from
//! this repository's code, so neither moves when the code does.

use axiom_proto::signing;

/// RFC 8032, section 7.1, test vector 1. The authority here is the Ed25519
/// specification rather than any version of any crate, so this fails if the
/// library is ever swapped for one that derives keys differently.
const RFC8032_SEED: &str = "9d61b19deffd5a60ba844af492ec2cc44449c5697b326919703bac031cae7f60";
const RFC8032_PUBLIC: &str = "d75a980182b10ab7d54bfed3c964073a0ee172f3daa62325af021a68f707511a";

/// The keypair in this repository's own .axiom/agent_key.json, generated by
/// `axiom keygen` under ed25519-dalek 2.2 before the bump to 3. Its authority is
/// that it was produced by the previous dependency version, which is exactly the
/// compatibility question a bump raises.
const PRE_BUMP_SEED: &str = "fabce92e26a9346b91f8c0dbdb8c41c954e9a346617a3cc238059d6aa401d763";
const PRE_BUMP_PUBLIC: &str = "142e576849d0c8fd66d5139c31b14cdde9b9c0619394dc245585b603b7b78a19";

#[test]
fn the_stored_private_key_is_an_rfc8032_seed() {
    assert_eq!(
        signing::public_key_of(RFC8032_SEED).expect("the RFC 8032 seed must load as a signing key"),
        RFC8032_PUBLIC,
        "the hex stored as a private key must be the 32-byte Ed25519 seed, \
         deriving the public key RFC 8032 gives for it"
    );
}

#[test]
fn a_key_written_by_the_previous_dependency_version_still_loads() {
    assert_eq!(
        signing::public_key_of(PRE_BUMP_SEED)
            .expect("a key written by an earlier axiom must still load"),
        PRE_BUMP_PUBLIC,
        "a private key already on disk must derive the public key it derived \
         before, or every attestation signed with it stops verifying"
    );
}

#[test]
fn a_generated_key_is_a_seed_of_the_same_shape() {
    let (private_hex, public_hex) = signing::generate_keypair();

    assert_eq!(
        private_hex.len(),
        64,
        "a private key is 32 bytes of hex, got {private_hex:?}"
    );
    assert_eq!(
        public_hex.len(),
        64,
        "a public key is 32 bytes of hex, got {public_hex:?}"
    );
    assert_eq!(
        signing::public_key_of(&private_hex).expect("a freshly generated key must load"),
        public_hex,
        "generate_keypair must return a pair that public_key_of agrees on, or \
         `axiom keygen` writes a .pub file that does not match its private key"
    );
}

#[test]
fn two_generated_keys_differ() {
    // A seed filled from a source that silently failed would be all zeroes, and
    // every check above would still pass.
    let (first, _) = signing::generate_keypair();
    let (second, _) = signing::generate_keypair();

    assert_ne!(
        first, second,
        "two generated keys must differ, or the seed is not coming from the OS"
    );
    assert_ne!(
        first,
        "0".repeat(64),
        "a generated seed must not be all zeroes"
    );
}
