[package]
name = "axiom-vmm"
version = "0.1.0"
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[dependencies]
axiom-proto = { path = "../axiom-proto" }
wasmtime.workspace = true
wasmtime-wasi.workspace = true
tokio.workspace = true
async-trait.workspace = true
anyhow.workspace = true
tracing.workspace = true
serde_json.workspace = true
